# Generated by Django 5.0.6 on 2024-05-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='biography',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='interests',
            new_name='talks_about',
        ),
    ]
