# Generated by Django 5.0.6 on 2024-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slg',
            field=models.SlugField(blank=True, max_length=300, null=True, unique_for_date='created'),
        ),
    ]
